# Generated by Django 2.2.7 on 2020-01-03 01:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('accountApp', '0003_auto_20191228_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='followers',
            field=models.ManyToManyField(related_name='_customuser_followers_+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customuser',
            name='following',
            field=models.ManyToManyField(related_name='_customuser_following_+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profile',
            name='age_range',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(10, '10대'), (20, '20대'), (30, '30대'),
                                                                        (40, '40대'), (50, '50대'), (60, '60대 이상')],
                                                   null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True),
        ),
    ]
