# Generated by Django 2.2.7 on 2020-01-07 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accountApp', '0006_auto_20200106_1157'),
        ('accountApp', '0004_auto_20200105_0051'),
    ]

    operations = [
    ]
