
# Generated by Django 2.2.7 on 2020-01-07 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contentsApp', '0006_auto_20200107_2227'),
        ('accountApp', '0008_auto_20200107_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='subscribes',
            field=models.ManyToManyField(to='contentsApp.Webtoon', blank=True),
        ),
    ]
