# Generated by Django 2.2.7 on 2020-01-11 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accountApp', '0009_profile_subscribe'),
        ('accountApp', '0004_auto_20200106_1635'),
    ]

    operations = [
    ]
