# Generated by Django 2.2.7 on 2020-01-16 15:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountApp', '0011_auto_20200111_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(db_index=True, max_length=255, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='relations',
            field=models.ManyToManyField(blank=True, related_name='_customuser_relations_+', through='accountApp.Relation', to=settings.AUTH_USER_MODEL),
        ),
    ]
