# Generated by Django 2.2.7 on 2019-12-24 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgeRatingSystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Cartoonist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='')),
                ('name', models.CharField(max_length=100)),
                ('text', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContentProvider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='')),
                ('name', models.CharField(max_length=100)),
                ('url', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Webtoon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('url', models.CharField(max_length=200)),
                ('age_rating', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='contentsApp.AgeRatingSystem')),
                ('cartoonists', models.ManyToManyField(to='contentsApp.Cartoonist')),
                ('content_provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contentsApp.ContentProvider')),
                ('tags', models.ManyToManyField(to='contentsApp.Tag')),
            ],
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('number', models.IntegerField()),
                ('title', models.TextField()),
                ('created', models.DateField()),
                ('isFree', models.BooleanField()),
                ('url', models.CharField(max_length=100)),
                ('webtoon', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contentsApp.Webtoon')),
            ],
        ),
    ]
