# Generated by Django 2.2.7 on 2020-01-04 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contentsApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartoonist',
            name='image',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='contentprovider',
            name='image',
            field=models.ImageField(default='', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='episode',
            name='image',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='webtoon',
            name='image',
            field=models.TextField(default=''),
        ),
    ]
