# Generated by Django 2.2.7 on 2020-01-05 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contentsApp', '0002_auto_20200105_0051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartoonist',
            name='image',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='webtoon',
            name='image',
            field=models.TextField(null=True),
        ),
    ]
