# Generated by Django 2.2.7 on 2020-01-07 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contentsApp', '0003_auto_20200105_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartoonist',
            name='image',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='webtoon',
            name='image',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='webtoon',
            name='url',
            field=models.URLField(),
        ),
    ]
