# Generated by Django 2.2.7 on 2020-01-07 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contentsApp', '0004_auto_20200107_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentprovider',
            name='url',
            field=models.URLField(default=''),
        ),
        migrations.AlterField(
            model_name='episode',
            name='image',
            field=models.URLField(default=''),
        ),
        migrations.AlterField(
            model_name='episode',
            name='url',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='webtoon',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='webtoon',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='webtoon',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='contentsApp.Tag'),
        ),
    ]
