# Generated by Django 2.2.7 on 2020-01-11 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contentsApp', '0006_auto_20200107_2227'),
        ('contentsApp', '0002_comment_post'),
    ]

    operations = [
    ]
