# Generated by Django 2.2.7 on 2020-01-11 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contentsApp', '0007_merge_20200111_2242'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
